#!/usr/bin/env sh

# bar settings
yabai -m config status_bar off
yabai -m config external_bar all:0:12

## Some random global settings
yabai -m config mouse_follows_focus on

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

yabai -m config window_border on
yabai -m config window_border_width 2
# yabai -m config active_window_border_topmost off
# yabai -m config active_window_border_color 0xfffabd2f # yellow
yabai -m config active_window_border_color 0xff83a598 # blue
# yabai -m config active_window_border_color 0xffd3869b # purple
yabai -m config normal_window_border_color 0xff665c54
# yabai -m config insert_window_border_color 0xffd75f5f

# Mouse settings
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move
yabai -m config mouse_drop_action swap

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 10

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^CiscoSparkHelper$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Cisco Webex Start$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Digital Colour Meter$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Zscaler" manage=off

echo "yabai configuration loaded.."
